name: CheckAndTest
on: [pull_request]
jobs:
  check-and-test:
    runs-on: ubuntu-20.04

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_DATABASE: grabook_test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.2.0'
      - run: npm install
      - name: Build frontend
        run: npm run build
      - name: Check Frontend Code
        run: npm run lint:dry
      # - name: Test Frontend
      #   run: npm run test
